package: inbox
version: '8.0.0-dev'
author: 'Alexander Walther'
supportpage: https://github.com/alexplusde/inbox

requires:
    php:
        version: '>8.1,<9'
    redaxo: ^5.18
    packages:
        yform: "^4"
        yform_spam_protection: "^1"
        auto_delete: "^1"

page:
    title: translate:inbox_title
    prio: 12
    block: system
    icon: rex-icon fa-envelope

pages:
    inbox:
        title: translate:inbox_title
        icon: rex-icon fa-envelope
        perm: inbox[]
    settings:
        title: translate:inbox_settings
        icon: rex-icon fa-gear
        itemClass: pull-right
        perm: admin
    docs:
        title: translate:inbox_docs
        subPath: README.md
        icon: rex-icon fa-info-circle
        itemClass: pull-right
        perm: admin

installer_ignore:
- .git
- .gitignore
- .github
- .php-cs-fixer.dist.php
